export const airports = [
  {
    code: "JFK",
    city: "New York",
    name: "John F. Kennedy International Airport",
  },
  {
    code: "LAX",
    city: "Los Angeles",
    name: "Los Angeles International Airport",
  },
  { code: "ORD", city: "Chicago", name: "O'Hare International Airport" },
  {
    code: "DFW",
    city: "Dallas",
    name: "Dallas/Fort Worth International Airport",
  },
  { code: "DEN", city: "Denver", name: "Denver International Airport" },
  {
    code: "SFO",
    city: "San Francisco",
    name: "San Francisco International Airport",
  },
  {
    code: "SEA",
    city: "Seattle",
    name: "Seattle-Tacoma International Airport",
  },
  { code: "LAS", city: "Las Vegas", name: "Harry Reid International Airport" },
  { code: "MCO", city: "Orlando", name: "Orlando International Airport" },
  { code: "MIA", city: "Miami", name: "Miami International Airport" },
  {
    code: "ATL",
    city: "Atlanta",
    name: "Hartsfield-Jackson Atlanta International Airport",
  },
  { code: "BOS", city: "Boston", name: "Logan International Airport" },
  {
    code: "PHX",
    city: "Phoenix",
    name: "Phoenix Sky Harbor International Airport",
  },
  {
    code: "IAH",
    city: "Houston",
    name: "George Bush Intercontinental Airport",
  },
  {
    code: "MSP",
    city: "Minneapolis",
    name: "Minneapolis-St Paul International Airport",
  },
  {
    code: "DTW",
    city: "Detroit",
    name: "Detroit Metropolitan Wayne County Airport",
  },
  {
    code: "PHL",
    city: "Philadelphia",
    name: "Philadelphia International Airport",
  },
  { code: "LGA", city: "New York", name: "LaGuardia Airport" },
  {
    code: "FLL",
    city: "Fort Lauderdale",
    name: "Fort Lauderdale-Hollywood International Airport",
  },
  {
    code: "BWI",
    city: "Baltimore",
    name: "Baltimore/Washington International Airport",
  },
  {
    code: "SLC",
    city: "Salt Lake City",
    name: "Salt Lake City International Airport",
  },
  {
    code: "DCA",
    city: "Washington",
    name: "Ronald Reagan Washington National Airport",
  },
  {
    code: "IAD",
    city: "Washington",
    name: "Washington Dulles International Airport",
  },
  { code: "SAN", city: "San Diego", name: "San Diego International Airport" },
  { code: "TPA", city: "Tampa", name: "Tampa International Airport" },
  { code: "PDX", city: "Portland", name: "Portland International Airport" },
  {
    code: "HNL",
    city: "Honolulu",
    name: "Daniel K. Inouye International Airport",
  },
  {
    code: "AUS",
    city: "Austin",
    name: "Austin-Bergstrom International Airport",
  },
  {
    code: "CLT",
    city: "Charlotte",
    name: "Charlotte Douglas International Airport",
  },
  {
    code: "STL",
    city: "St. Louis",
    name: "St. Louis Lambert International Airport",
  },
  { code: "EWR", city: "Newark", name: "Newark Liberty International Airport" },
  {
    code: "MDW",
    city: "Chicago",
    name: "Chicago Midway International Airport",
  },
  { code: "BNA", city: "Nashville", name: "Nashville International Airport" },
  { code: "OAK", city: "Oakland", name: "Oakland International Airport" },
  {
    code: "RDU",
    city: "Raleigh",
    name: "Raleigh-Durham International Airport",
  },
  {
    code: "MCI",
    city: "Kansas City",
    name: "Kansas City International Airport",
  },
  {
    code: "SAT",
    city: "San Antonio",
    name: "San Antonio International Airport",
  },
  {
    code: "RSW",
    city: "Fort Myers",
    name: "Southwest Florida International Airport",
  },
  { code: "SMF", city: "Sacramento", name: "Sacramento International Airport" },
  {
    code: "IND",
    city: "Indianapolis",
    name: "Indianapolis International Airport",
  },
  {
    code: "CMH",
    city: "Columbus",
    name: "John Glenn Columbus International Airport",
  },
  { code: "PIT", city: "Pittsburgh", name: "Pittsburgh International Airport" },
  {
    code: "CVG",
    city: "Cincinnati",
    name: "Cincinnati/Northern Kentucky International Airport",
  },
  {
    code: "CLE",
    city: "Cleveland",
    name: "Cleveland Hopkins International Airport",
  },
  {
    code: "ABQ",
    city: "Albuquerque",
    name: "Albuquerque International Sunport",
  },
  {
    code: "MKE",
    city: "Milwaukee",
    name: "Milwaukee Mitchell International Airport",
  },
  { code: "OMA", city: "Omaha", name: "Eppley Airfield" },
  { code: "ONT", city: "Ontario", name: "Ontario International Airport" },
  { code: "BUR", city: "Burbank", name: "Hollywood Burbank Airport" },
  {
    code: "ANC",
    city: "Anchorage",
    name: "Ted Stevens Anchorage International Airport",
  },
];
